runtime: go
api_version: go1
application: tasktracker-1337

inbound_services:
- warmup

handlers:
- url: /static
  static_dir: static

- url: /
  static_files: templates/body.html
  upload: templates/body.html

- url: /cron/.*
  script: _go_app
  login: admin

- url: /_ah/warmup
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
